name: krish_ai
description: Krish AI Assistant - A modern AI assistant with voice, face recognition, and automation capabilities.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  
  # UI/UX
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.4.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  rive: ^0.11.4
  
  # Animation
  flutter_animate: ^4.2.0
  animations: ^2.0.7
  
  # Navigation
  go_router: ^9.0.3
  
  # State Management
  flutter_riverpod: ^2.3.6
  
  # Network
  dio: ^5.2.1+1
  connectivity_plus: ^4.0.1
  web_socket_channel: ^2.4.0
  
  # Local Storage
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Firebase
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  
  # Camera & Media
  camera: ^0.10.5+2
  image_picker: ^1.0.0
  photo_view: ^0.14.0
  video_player: ^2.7.0
  
  # Voice & Audio
  just_audio: ^0.9.34
  record: ^4.4.4
  speech_to_text: ^6.3.0
  flutter_tts: ^3.7.0
  
  # Face Detection
  google_ml_kit: ^0.16.1
  face_detection: ^0.0.2
  
  # Biometrics
  local_auth: ^2.1.6
  
  # Charts & Visualization
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^22.1.39
  
  # Utilities
  permission_handler: ^10.4.1
  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  intl: ^0.18.1
  
  # ML & AI
  tflite_flutter: ^0.10.1
  tensorflow_lite_flutter: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  branding: assets/images/branding.png
  color_dark: "#000000"
  image_dark: assets/images/splash_dark.png
  branding_dark: assets/images/branding_dark.png

  android_12:
    image: assets/images/splash_android12.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash_android12_dark.png
    icon_background_color_dark: "#000000"
